[package]
name = "bevy_action_orc"
version = "0.1.0"
edition = "2024"
description = "Bevy ECS integration for the action-orc."
repository = "https://github.com/TigranKirakosov/bevy_action_orc"
license = "MIT OR Apache-2.0"

[dependencies]
action-orc = { version = "0.1.0" }
bevy = { version = "0.19.1", default-features = false }
